version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.5
  aws-cli: circleci/aws-cli@0.1.6

_defaults: &defaults
  machine:
    docker_layer_caching: true
  working_directory: ~/repo
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3000m
    SBT_OPTS: -Xmx2000m
    TERM: dumb

workflows:
  version: 2
  development:
    jobs:
    - build
    - test
    - style
    - publish:
        context: nexus
        requires:
        - build
        - test
        - style
        filters:
          tags:
            only: /^v.*/
          branches:
            only:
              - master

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Compile
        command: cat /dev/null | sbt test:compile

    - save_cache:
        paths:
        - ~/.ivy2/cache
        - ~/.m2
        - ~/.sbt
        - target
        key: v1-dependencies-{{ checksum "build.sbt" }}

  # Runs all tests which have no external dependencies
  test:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Run unit tests
        command: cat /dev/null | sbt +test

    - save_cache:
        paths:
        - ~/.ivy2/cache
        - ~/.m2
        - ~/.sbt
        - target
        key: v1-dependencies-{{ checksum "build.sbt" }}

  # Checks formatting
  style:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Run scalafmt checks
        command: cat /dev/null | sbt fmtCheck

  # Release the next version
  publish:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Release version and bump snapshot
        command: cat /dev/null | sbt ci-release
